name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull htmljeday/skillup-laravel-forum:latest

      - name: Stop old containers
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml down || true

      - name: Start containers (prod)
        run: sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d


        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build Docker Image
        run: sudo docker build -t htmljeday/skillup-laravel-forum .

      - name: Push Docker Image
        run: sudo docker push htmljeday/skillup-laravel-forum:latest
