name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull latest Docker image
        run: sudo docker pull htmljeday/skillup-laravel-forum:latest

      - name: Stop and remove old containers
        run: sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans || true

      - name: Start containers in production mode
        run: sudo docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

      - name: Clean up unused images
        run: sudo docker image prune -f
