name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_testing
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: testing

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel_testing
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy .env file
        run: |
          cp .env.example .env
          echo "APP_KEY=" >> .env

      - name: Create testing environment file
        run: |
          cat > .env.testing << 'EOL'
          APP_NAME=Laravel
          APP_ENV=testing
          APP_KEY=base64:4n2TiTbnbpG140pwQOPcVY+KfrUcPeBbtbchp3hBcBQ=
          APP_DEBUG=true
          APP_URL=http://localhost

          LOG_CHANNEL=stack
          LOG_LEVEL=debug

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=laravel_testing
          DB_USERNAME=root
          DB_PASSWORD=root

          BROADCAST_DRIVER=log
          CACHE_DRIVER=array
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=array
          SESSION_LIFETIME=120

          MAIL_MAILER=log
          EOL

      - name: Generate app key
        run: php artisan key:generate

      - name: Clear config cache
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"3306" --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 1
          done

      - name: Run migrations
        run: php artisan migrate:fresh --force --env=testing

      - name: Run seed
        run: php artisan db:seed --force --env=testing

      - name: Run tests
        id: run_tests
        run: |
          php artisan config:clear
          php artisan cache:clear
          ./vendor/bin/phpunit --configuration phpunit.github.xml --testsuite Unit,Feature --stop-on-failure
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Print test exit code
        run: |
          echo "Test exit code: ${{ steps.run_tests.outputs.exit_code }}"

      # These steps only run if tests pass
      - name: Login Dockerhub
        if: success()
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        if: success()
        run: docker build -t htmljeday/skillup-laravel-forum:latest .

      - name: Push to Dockerhub
        if: success()
        run: docker push htmljeday/skillup-laravel-forum:latest
