name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel_testing
      DB_USERNAME: root
      DB_PASSWORD: root

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Copy .env files
        run: |
          cp .env.example .env
          cp .env.testing.ci .env.testing

      - name: Generate app key
        run: php artisan key:generate

      - name: Configure database
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run seed
        run: php artisan db:seed

      - name: Run tests
        run: ./run-tests.sh --stop-on-failure && echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Print test exit code
        run:
          echo "Test exit code: ${{ steps.run_tests.outputs.exit_code }}"




      # These steps only run if tests pass

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t htmljeday/skillup-laravel-forum:latest .

      - name: Push to Dockerhub
        run: docker push htmljeday/skillup-laravel-forum:latest
